### ISSUE TITLE
Solid fill wont go away and seems misaligned

### ISSUE THREAD

**Issue by samshott** [tylermorganwall/rayshader#117]
When using plot_3d I end up with a Solid fill underneath even when solid is set to FALSE.  I also the fill seems misaligned from the hillshade and elevation matrix even though I have confirmed the dimensions of both are identical before and after turning them into a matrix and an array.

Here is the code I'm using for the plot_3d Function:
`plot_3d(rgb_CO_array, SW_CO_Ele_Matrix, windowsize = c(1600,900),
        zscale = 10, shadowdepth = -50, zoom = 0.5, theta = -45, 
        fov = 100, background = '#F2E1D0', shadowcolor = '#523E2B',
        solid = FALSE)`

Here is what I am getting as an output:
![RayshaderIssue](https://user-images.githubusercontent.com/64446365/86305954-cd91ec80-bbc7-11ea-9189-c4bb93d32ff4.png)

Unsure why that's either of these is occurring
The rest of my code can be seen [here](https://github.com/samshott/Creating-a-3d-map-in-R/blob/master/R_3dMap)

**Comment by tylermorganwall** [comment]
That doesn't appear to be the solid rendering: it appears your imagery doesn't fully cover the extent of the underlying elevation matrix, so those areas without imagery are being rendered in black. This is because the imagery is at a slight angle, so the extent includes some non-imagery areas. Slightly decrease the size of the crop to remove the imagery-less areas.
