### ISSUE TITLE
render_snapshot(clear=TRUE) doesn't work

### ISSUE THREAD

**Issue by Savedbygrace98** [tylermorganwall/rayshader#211]
I tried to plot a population map with Rayshader. But I encountered a problem: 
"In rgl.snapshot(filename, fmt, top) :
  this build of rgl does not support snapshots"
![Rprogrammiing](https://user-images.githubusercontent.com/74196320/153653767-a6c9be63-743e-4019-8228-e094d5f48158.png)
"
And I have a total black image.

**Comment by tylermorganwall** [comment]
You are using the NULL rgl device, which does not support snapshots. You can either reinstall rgl with OpenGL support, or set `render_snapshot(software_render = TRUE)` which uses a software renderer to take snapshots, rather than rgl. I recommend setting a `cache_filename` in `render_snapshot()` if you choose the second method, otherwise it will be much slower.

**Comment by Savedbygrace98** [comment]
Please, explain me clearly, step by step both methods. I'm almost a total newbie with R.
