### ISSUE TITLE
ERROR: compilation failed for package 'rayvertex'

### ISSUE THREAD

**Issue by dougaltoms** [tylermorganwall/rayshader#230]
Hi, 

Fairly new to R, so maybe an obvious fix.

`devtools::install_github("tylermorganwall/rayshader")` fails to install the rayshader package and I get the following errors:

> .../Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:77:17: error: expected ';' after top level declarator
> constexpr size_t
>                 ^
>                 ;
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 16 warnings and 20 errors generated.
> make: *** [filltri.o] Error 1
> ERROR: compilation failed for package ‘rayvertex’`
> 
>

> `ERROR: dependency ‘rayvertex’ is not available for package ‘rayshader’
> * removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/rayshader’
> Warning messages:
> 1: In i.p(...) :
>   installation of package ‘/var/folders/n4/dm13c5h531g1yv38mn29kb300000gn/T//RtmpcZOH3U/file142816bd8f860/rayvertex_0.3.4.tar.gz’ had non-zero exit status
> 2: In i.p(...) :
>   installation of package ‘/var/folders/n4/dm13c5h531g1yv38mn29kb300000gn/T//RtmpcZOH3U/file142816fc584f7/rayshader_0.28.0.tar.gz’ had non-zero exit status`

Any ideas where I am going wrong? Thanks in advance

**Comment by tylermorganwall** [comment]
Make sure to install the rayvertex package and then try installing the dev version of rayshader

```
options(repos = c(
  ropensci = 'https://tylermorganwall.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))
  
# Download and install rayshader in R
install.packages(c('rayshader','rayvertex'))
 
```

**Comment by PietroViolo** [comment]
Hi, I have the same issue. The problem lies when in fact, we try to install rayvertex, which halts the installation of rayshader.
I tried your solution Tyler, but with no success. 
I also noticed that I'm having trouble installing rgdal and RcppArmadillo....
I'm on Mac if that changes anything, here's the full error when we try to install rayvertex:

Thanks for your time.

In file included from filltri.cpp:1:
In file included from ./filltri.h:7:
In file included from /Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread.h:9:
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/RMonitor.hpp:45:33: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    RMonitor(RMonitor const&) = delete;
                                ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/RMonitor.hpp:47:22: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    RMonitor(RMonitor&&) = delete;
                     ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/RMonitor.hpp:47:28: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    RMonitor(RMonitor&&) = delete;
                           ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/RMonitor.hpp:49:44: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    RMonitor& operator=(RMonitor const&) = delete;
                                           ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/RMonitor.hpp:51:34: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    RMonitor& operator=(RMonitor &&) = delete;
                                 ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/RMonitor.hpp:51:40: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    RMonitor& operator=(RMonitor &&) = delete;
                                       ^
In file included from filltri.cpp:1:
In file included from ./filltri.h:7:
In file included from /Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread.h:12:
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:30:16: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
    Thread() = default;
               ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:31:23: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    Thread(Thread&) = delete;
                      ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:32:29: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
    Thread(const Thread&) = delete;
                            ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:33:18: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    Thread(Thread&& other)
                 ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:38:35: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
    template<class Function, class... Args> explicit
                                  ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:39:20: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    Thread(Function&& f, Args&&... args)
                   ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:39:30: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    Thread(Function&& f, Args&&... args)
                             ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:50:14: error: expected ';' at end of declaration list
    ~Thread() noexcept
             ^
             ;
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:59:29: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    Thread& operator=(Thread&& other)
                            ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:67:29: error: expected ';' at end of declaration list
    void swap(Thread& other) noexcept
                            ^
                            ;
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:41:9: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
        auto f0 = [=] () {
        ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:41:19: error: expected expression
        auto f0 = [=] () {
                  ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:45:9: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
        auto task = std::packaged_task<void()>(f0);
        ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:47:9: error: use of undeclared identifier 'thread_'
        thread_ = std::thread(std::move(task));
        ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/Thread.hpp:61:13: error: use of undeclared identifier 'thread_'
        if (thread_.joinable())
            ^
In file included from filltri.cpp:1:
In file included from ./filltri.h:7:
In file included from /Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread.h:13:
In file included from /Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/ThreadPool.hpp:12:
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:65:8: error: unknown type name 'constexpr'
static constexpr std::memory_order relaxed = std::memory_order_relaxed;
       ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:65:23: error: cannot define or redeclare 'memory_order' here because namespace 'mem' does not enclose namespace 'std'
static constexpr std::memory_order relaxed = std::memory_order_relaxed;
                 ~~~~~^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:65:35: error: expected ';' after top level declarator
static constexpr std::memory_order relaxed = std::memory_order_relaxed;
                                  ^
                                  ;
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:66:8: error: unknown type name 'constexpr'
static constexpr std::memory_order acquire = std::memory_order_acquire;
       ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:66:23: error: cannot define or redeclare 'memory_order' here because namespace 'mem' does not enclose namespace 'std'
static constexpr std::memory_order acquire = std::memory_order_acquire;
                 ~~~~~^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:66:35: error: expected ';' after top level declarator
static constexpr std::memory_order acquire = std::memory_order_acquire;
                                  ^
                                  ;
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:67:8: error: unknown type name 'constexpr'
static constexpr std::memory_order release = std::memory_order_release;
       ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:67:23: error: cannot define or redeclare 'memory_order' here because namespace 'mem' does not enclose namespace 'std'
static constexpr std::memory_order release = std::memory_order_release;
                 ~~~~~^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:67:35: error: expected ';' after top level declarator
static constexpr std::memory_order release = std::memory_order_release;
                                  ^
                                  ;
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:68:8: error: unknown type name 'constexpr'
static constexpr std::memory_order seq_cst = std::memory_order_seq_cst;
       ^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:68:23: error: cannot define or redeclare 'memory_order' here because namespace 'mem' does not enclose namespace 'std'
static constexpr std::memory_order seq_cst = std::memory_order_seq_cst;
                 ~~~~~^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:68:35: error: expected ';' after top level declarator
static constexpr std::memory_order seq_cst = std::memory_order_seq_cst;
                                  ^
                                  ;
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:77:1: error: unknown type name 'constexpr'
constexpr size_t
^
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppThread/include/RcppThread/quickpool.hpp:77:17: error: expected ';' after top level declarator
constexpr size_t
                ^
                ;
fatal error: too many errors emitted, stopping now [-ferror-limit=]
16 warnings and 20 errors generated.
make: *** [filltri.o] Error 1
ERROR: compilation failed for package ‘rayvertex’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/rayvertex’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/yt/ps_gx1y932323r2tny0mjncc0000gn/T//RtmpdRfcqt/fileb80f14eb765b/rayvertex_0.3.4.tar.gz’ had non-zero exit status

**Comment by gabrielluishernandez** [comment]
Hello, 
Unfortunately, I am encountering similar issues with dependencies including RcppArmadillo, terra, and raster.
![image](https://user-images.githubusercontent.com/20094334/196028477-d1960a3c-681a-496d-ace5-c54ad8f07307.png)

I also tried the solution proposed by @tylermorganwall 

Thanks a lot for your help, I am looking forward to using this promising tool. 

Gabriel

**Comment by tylermorganwall** [comment]
The first issue is an issue installing `RcppThread`, so I would open an issue at https://github.com/tnagler/RcppThread to report it.

@gabrielluishernandez I would uninstall all said packages, restart R, and try reinstalling them. If that doesn't work, uninstall and reinstall R entirely. I would recommend that process for all installation issues of this sort. The issue appears to be something wrong with your R installation (either permissions issues or something else).

**Comment by gabrielluishernandez** [comment]
Thank you for your help. I have managed to install rayshader!!!
-Reinstalled R and Rstudio.
-Manually install xquartz from: https://macappstore.org/xquartz/
-install.packages("rgl") https://www.rdocumentation.org/packages/rgl/versions/0.110.2
-Restart machine
-devtools::install_github("tylermorganwall/rayshader")
-Begin to have fun with rayshader.

Thanks again,
Gabriel
