### ISSUE TITLE
`plot_3d` doesn't respond to mouse wheel.

### ISSUE THREAD

**Issue by dmurdoch** [tylermorganwall/rayshader#250]
This StackOverflow question https://stackoverflow.com/q/74813962/2554330 found that the mouse wheel doesn't work in recent `rayshader` displays using `plot_3d`.

The problem is that it is using the low level `rgl::rgl.surface()` function to open the display, which doesn't initialize any setting on the mouse wheel.  I recommend against using any of the `rgl.*` functions; they require a lot of care to get right, and the `*3d` functions (i.e. `surface3d` in this case) handle a lot of things more automatically.  There are some differences between the argument lists, so it's not a completely trivial change, but I think you'd be better off doing it. 

Any other `rgl.*` functions should similarly be replaced, so you might want a quick fix in the meantime, and probably the quickest one is to open a new window using `next3d()` unless a user asks to add the display to the current window.  `next3d()` will switch to the next panel if a multi-panel display is in use, will clear a single page display, or will open a new display if there is none found.

**Comment by dmurdoch** [comment]
I've just merged a change to `rgl` that fixes this issue, though it may introduce others.  However, I'm not planning to send this to CRAN for a month or two.

**Comment by tylermorganwall** [comment]
Thank you for issuing the recent fix for the camera issues people have been having. My primary reason for using `rgl.surface()` over `surface3d() `is all the coordinate systems I use have +y as the vertical axis, and there's no option to set the `coords` argument in `surface3d()` to keep that orientation. If you added the option to set coords in `surface3d()` rather than hard coding it in, I could switch over for that particular function. 

For all the other rgl.* functions I used, the camera defaulting to `polar` vs `trackball` was the primary reason for not switching. Now that I see how to set that for the user, I'll just make sure to set it after my call.

**Comment by dmurdoch** [comment]
The `rgl.surface` function has a `coords` argument that `surface3d` fixes as `c(1, 3, 2)`.  (This matches the coordinate convention used by the base `persp()` function.) It would be easy to make that an optional argument to `surface3d`, i.e. to rewrite it as

```
new_surface3d <- function(x,y=NULL,z=NULL,...,normal_x=NULL,normal_y=NULL,normal_z=NULL, coords = c(1, 3, 2)) {
  .check3d(); save <- material3d(); on.exit(material3d(save))
  do.call("rgl.surface", c(list(x=x,y=z,z=y,coords=coords,
                                normal_x=normal_x,normal_y=normal_z,normal_z=normal_y), 
                           .fixMaterialArgs(..., Params = save)))
}
environment(new_surface3d) <- environment(surface3d)
```

and then you could call it with `coords = 1:3`.  Could you try this out and see if it works for you?  I'd be happy to make that change in `rgl` if it solves your problem.

**Comment by dmurdoch** [comment]
Never mind, that doesn't work.  Let me think about this a bit more.

**Comment by tylermorganwall** [comment]
This should be fixed in the latest version on github.
