### ISSUE TITLE
detect_water swaps north/south vs. original matrix?

### ISSUE THREAD

**Issue by apsteinmetz** [tylermorganwall/rayshader#40]
I was trying to use `detect_water` for feature engineering outside of the plotting workflow and I discovered a weird behavior.  The latitude of the matrix produced by `detect_water` seems to swap north with south.  You can see this by converting each matrix to a dataframe and plotting through ggplot.  Perhaps the problem lies with they way I `melt` the matrix to a data frame but I use the same procedure for the water matrix and the original matrix. 

This doesn't show up in the normal rayshader plotting workflow, obviously.

```
library(dplyr)
library(reshape2)
library(ggplot2)
library(rayshader)

# set below waterline points to zero so detect_water finds them
mont_depth <- montereybay
mont_depth[which(montereybay<0)] = 0
watermap <- detect_water(mont_depth)

# turn watermap matrix into a data frame
watermap_df <- watermap %>% 
  melt(value.name = "is_water") %>% 
  mutate(is_water = as.factor(is_water))

# turn original matrix into a data frame and merge with watermap
elev <- montereybay %>% 
  melt(value.name = "elev") %>%
  mutate(is_land = as.factor(ifelse(elev < 0 ,0,1))) %>% 
  full_join(watermap_df) %>% 
  as_tibble()
#> Joining, by = c("Var1", "Var2")

#illustrate that latitude for watermap is north/south swapped vs. original matrix
elev %>% 
  filter(elev < 0) %>% 
  ggplot() + 
  geom_tile(aes(Var1,Var2,fill=is_land),alpha=0.5) +
  geom_tile(data=watermap_df,aes(Var1,Var2,fill=is_water),alpha=0.8)
```

**Comment by tylermorganwall** [comment]
This discrepancy is due to the differences in standard coordinate systems in image processing / matrices (top to bottom) and function plotting (y axis points up). It should be consistent within `rayshader` (e.g. the output of `detect_water()` should appear in its correct orientation in `plot_map()`. You can call the internal function `rayshader:::flipud()` if you ever need to convert a matrix, or just do it yourself (it's a single line of code for matrices `flipud = function(x) x[nrow(x):1,]`.
