### ISSUE TITLE
How to reduce the size of the .stl output file for 3D print

### ISSUE THREAD

**Issue by longhaivo** [tylermorganwall/rayshader#58]
Many thanks to Tyler for the tip about [movie length](https://github.com/tylermorganwall/rayshader/issues/57). I have another question: I am able to produce an .stl file for my 3D scatterplot using the 'save_3dprint' function. However, I think because I have too many data points (15,400 to be exact), the output file exceeds 200mb. Anything we can do to reduce the file size? I tried reduce the plot dimension, for example:

`mtcars_gg = ggplot(mtcars) + 
  geom_point(aes(x=mpg,color=cyl,y=disp),size=2) +
  scale_color_continuous(limits=c(0,8)) +
  ggtitle("mtcars: Displacement vs mpg vs # of cylinders") +
  theme(title = element_text(size=8),
        text = element_text(size=12)) ;
mtcars_gg;
plot_gg(mtcars_gg, height=3, width=3.5, multicore=TRUE, 
        pointcontract = 0.7, soliddepth=-50);
save_3dprint('mtcars1.stl', maxwidth = 4, unit = "in");`

It appears that changing 'maxwidth = 4' to 'maxwidth=2' doesn't affect the file size. The file size for this mtcars example is 90mb, which is surprising because we don't have as many data points here. Perhaps the 'soliddepth', or thickness, parameter adds to the size.
And I understand that the 3D print version of the plot will always be colourless?

Thanks,
Long

**Comment by tylermorganwall** [comment]
The filesize of the 3D model is determined by the width and height arguments in the plot_3d function. Decrease those to shrink the file—you may have to adjust the ggplot accordingly. The actual data in the plot should not change the filesize of the model. The save_3dprint function width and height arguments change the physical size for printing, but do not affect the .stl otherwise. Generally, these files will be rather big.

And for STL files, yes: there is no color.

**Comment by longhaivo** [comment]
Thank you, as you said, adjusting the 'height' and 'width' parameters of the 'plot_gg' function solves this issue!
