### ISSUE TITLE
Is it possible to overlay a data raster on top of a map file?

### ISSUE THREAD

**Issue by palewire** [tylermorganwall/rayshader#63]
As [chronicled on Twitter](https://twitter.com/palewire/status/1149701830391152641), I've been able to use Rayshader to create a 3D map of earthquake intensity data. I'd love map this on top of a traditional terrain elevation file. Is it possible to combine two layers into one 3D map?

**Comment by tylermorganwall** [comment]
if you want to overlay the 2D data on the 3D topographic surface, that’s easy: just use the add_overlay function with an RGB array of your data. To overlay a floating 3D surface, you can create the 3D topographic map and then call plot_3d() a second time with the earthquake intensity data and overlay (you’ll probably want ‘solid = FALSE’ in the call). You’ll just have to offset the data and adjust the zscale to make sure it’s floating above the surface, since the data and the topographic map obviously have different scales.

**Comment by tillrose** [comment]
Might be related but I'm not really sure.
I'd like to combine two raster files, one with height and one with some additional spatial data, e.g. surface temperature.  I'm struggling to find a way to plot the topographic surface with an informational texture. Might be easy with plot_gg but I don't find a way to map something else than the height to the fill aesthetic…

**Comment by tylermorganwall** [comment]
I believe this is all supported now in rayshader with the `add_overlay()` function, so I'm going to close this issue.
